name: Process Transcripts
on:
  push:
    paths:
      - 'transcripts/**'

jobs:
  process-transcripts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Process Transcripts
        shell: bash
        run: |
          # Create processed directory if it doesn't exist
          mkdir -p processed
          
          # Initialize index file as empty array
          echo "[]" > processed/index.json
          
          # Check if there are any json files
          shopt -s nullglob
          for file in transcripts/*.json; do
            if [ -f "$file" ]; then
              # Calculate hash
              HASH=$(sha256sum "$file" | awk '{print $1}')
              
              # Process file and append to temporary file
              jq --arg hash "$HASH" --arg filename "$file" '
                {
                  id,
                  userId,
                  channelName,
                  timestamp,
                  hash: $hash,
                  originalFile: $filename
                }
              ' "$file" >> processed/temp.json
              
              # Copy the file with hashed name
              cp "$file" "processed/${HASH}.json"
            fi
          done
          
          # If we processed any files, combine them into an array
          if [ -f processed/temp.json ]; then
            # Combine all objects into an array
            jq -s '.' processed/temp.json > processed/index.json
            # Clean up temp file
            rm processed/temp.json
          fi
          
          # List contents for debugging
          echo "Contents of processed directory:"
          ls -la processed/
          
          echo "Content of index.json:"
          cat processed/index.json

      - name: Deploy to Protected Branch
        if: success()
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add processed/
          git commit -m "Process transcripts" || echo "No changes to commit"
          git push origin HEAD:protected --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
