name: Manage Transcripts
on:
  push:
    paths:
      - 'transcripts/**'

jobs:
  process-transcripts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Process Transcripts
        run: |
          mkdir -p processed
          for file in transcripts/*.json; do
            # Create a hash of the content to obscure the filename
            HASH=$(sha256sum "$file" | cut -d' ' -f1)
            # Create index entry with minimal info
            jq -c '{
              id: .id,
              userId: .userId,
              channelName: .channelName,
              timestamp: .timestamp,
              hash: $HASH
            }' "$file" >> processed/index.json
            # Move full transcript to hashed filename
            mv "$file" "processed/$HASH.json"
          done
          
      - name: Deploy to Protected Branch
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git checkout -b protected
          git add processed/
          git commit -m "Process transcripts"
          git push origin protected --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
